services:
  postgres:
    image: postgres:17.2
    container_name: microdata_prueba_database
    environment:
      POSTGRES_DB: microdata_prueba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: microdata_prueba_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microdata_prueba
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  pgdata:
